---
- hosts: centos

  tasks:
  - name: add user "cwaniaczek"
    user:
      name: cwaniaczek
      comment: "Privileged User"
      group: devops
      groups: wheel
      shell: /bin/bash
      password: papa
      create_home: yes
...

      
