---
- hosts: centos

  tasks:
  - name: add user "cwaniaczek"
    user:
      name: cwaniaczek
      comment: "Privileged User"
      group: devops
      groups: wheel
      append: yes
      shell: /bin/bash
      password: 458845tM!
      password_lock: no
      create_home: yes
...

      
