---
- hosts: centos

  tasks:
  - name: add user "cwaniaczek"
    user:
      name: cwaniaczek
      comment: "Privileged User"
      group: devops
      groups: wheel
      append: yes
      shell: /bin/bash
      create_home: yes
  - name: Unlock password and set it to empty
      command: passwd -d cwaniaczek
  - name: Expire password
      command: chage -d 0 cwaniaczek
...

      
