---
- hosts: ubuntu3,centos3

  tasks:
    - name: Create group for players
      group:
        name: players
        gid: 2010
        state: present

    - name: create wheel group for admins
      group:
        name: superAdmins
        gid: 2011
        state: present


    - name: create additonal group for juniors
      group:
        name: juniors
        gid: 2012
        state: present

    - name: create additonal group for devops
      group:
        name: devops
        gid: 2013
        state: present


    - name: Create user and add him to player group
      user:
        name: player
        comment: "Privileged User"
        uid: 2001
        group: players
        groups: superAdmins,juniors,devops
        apend: yes
        shell: /bin/bash
      when: ansible_distribution == 'CentOS'


    - name: Add user junior devops
      user:
        name: newJuniorDevops
        comment: "Content creator UnPrivileged User"
        uid: 2003
        group: juniors
        groups: devops
        shell: /bin/bash
      when: ansible_distribution == 'Ubuntu'

    - name: Remove user "Games" from remote server
      user:
        name: games
        state: absent
        remove: yes

  # Handlers: handlers that are executed as a notify key from a task

# Three dots indicate the end of a YAML document
...
